---
# A playbook for testing all roles.
- hosts: test
  sudo: yes
  vars:
    dest_folder: /opt/xinwei

  roles:
    - common
    - docker
    - redis
    - mongodb
    - nodejs
    # - xinwei_api
    - nginx
      nginx_http_params:
        sendfile: "on"
        access_log: "/var/log/nginx/access.log"
      nginx_sites:
       - server:
          file_name: xinwei_api
          listen: 80
          server_name: localhost
          root: "/var/www/xinwei"
         location:
            - name: /
              try_files: "$uri $uri/ /index.html"
            - name: /images/
              try_files: "$uri $uri/ /index.html"
       - server:
          file_name: xinwei_doc
          listen: 8080
          server_name: localhost
          root: "/var/www/xinwei_doc"
         location:
            - name: /
              try_files: "$uri $uri/ /index.html"
            - name: /images/
              try_files: "$uri $uri/ /index.html"
