---

- name: "Install docker apt key"
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present
  tags:
    - docker
    - apt_key

- name: "Install docker apt repository"
  apt_repository: repo="deb https://get.docker.com/ubuntu docker main" state=present
  tags:
    - docker
    - apt_repository

- name: Update apt-cache
  apt: update_cache=yes
  tags:
    - docker
    - apt_cache

- name: "Install docker package"
  apt: name=lxc-docker state=present
  tags:
    - docker
    - install

- name: "Configure docker host"
  lineinfile: >
    dest=/etc/default/docker
    state=present
    regexp='^#?DOCKER_OPTS='
    line='DOCKER_OPTS="{{ docker_options }}"'
  when: docker_options is defined
  notify: restart docker
  tags:
    - docker
    - config

- name: Install common python packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - python-setuptools
    - python-pip
  tags:
    - docker
    - python

# https://github.com/angstwad/docker.ubuntu/issues/44
- name: Install docker-py
  pip: name=docker-py version=1.2.2
  tags:
    - docker
    - python
